services:
  php:
    image: php:8.2-apache
    container_name: php_lab3
    ports:
      - "8080:80"       # доступ к серверу через http://localhost:8080
    volumes:
      - ./:/var/www/html  # монтируем текущую папку в контейнер
